import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignedOut,
  SignedIn,
  UserButton,
} from "@clerk/nextjs";
import Link from "next/link";
import { Providers } from "./providers";
import { NavigationMenu, NavigationMenuItem, NavigationMenuList } from "@/components/ui/navigation-menu";
import { Button } from "@/components/ui/button";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider signInFallbackRedirectUrl="/dashboard" signUpFallbackRedirectUrl="/dashboard" afterSignOutUrl="/">
          <Providers>
            <nav className="flex items-center justify-between px-6 py-4 border-b">
              <NavigationMenu>
                <NavigationMenuList>
                  <NavigationMenuItem className="mx-3">
                    <Link href="/">Inicio</Link>
                  </NavigationMenuItem>
                  <NavigationMenuItem className="mx-3">
                    <Link href="/about">Acerca de</Link>
                  </NavigationMenuItem>
                  {/* Agrega más items aquí */}
                </NavigationMenuList>
              </NavigationMenu>
              <div>
                <SignedIn>
                  <UserButton />
                </SignedIn>
                <SignedOut>
                  <Link href="/sign-in">
                    <Button>Iniciar sesión</Button>
                  </Link>
                </SignedOut>
              </div>
            </nav>
            {children}
          </Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}
